### ISSUE TITLE
Symbol size in "symbol header"

### ISSUE THREAD

**Issue by Bastian35022** [openrq-team/OpenRQ#4]
Great library, thanks a lot for making it available to us. =)

Question:
In RaptorQ, the FEC Payload ID (4 bytes) precedes every symbol, and carries the source block number and the encoding symbol ID. I noticed that you also add the symbol size (4 bytes) after that in `writeTo(ByteBuffer buffer)` of class `AbstractEncodingPacket`. Any reason to do this? It does not seem to be compliant to the IETF spec (RFC 6330).

**Comment by rjpfonseca** [comment]
Hi. Excellent question!

To get straight to the point, the reason we decided to include the length of the symbol(s) in the `writeTo()` methods of the `EncodingPacket` class, was to solve the problem of how to tell the receiver how many symbols are contained inside a received encoding packet (recall that a packet may contain multiple symbols).

We decided to use the total length of the symbols data to inform the receiver of how many symbols it should parse when a `parsePacket()` or `readPacketFrom()` method of the `DataDecoder` class is called, and an array/buffer/stream of bytes containing the symbols data is passed as parameter. We could have used the number of symbols instead, and perhaps that might have made the purpose of those extra 4 bytes more clear to the user.

This decision was taken in order to make things easier for the user, so that they should not have to worry about specifying the number of symbols to a RaptorQ decoder (a `DataDecoder` object). However, an `EncodingPacket` object also provides the symbols data and the number of symbols in separate methods, so in theory a user can use the separate information and build their own packets using whatever format they wish.

For now, at least, it is only possible for a `DataDecoder` object to receive and parse `EncodingPacket` objects from data containing our format, i.e., the FEC Payload ID, followed by the symbols data length, followed by the symbols data itself. Now that I'm thinking, we should provide additional methods in the future, in the `DataDecoder` class, that receive the symbols data and the number of symbols as separate parameters.

**Comment by rjpfonseca** [comment]
@Bastian35022

In this comment I will separately address your concern regarding the compliance to the IETF spec (RFC 6330) of our addition of 4 bytes containing the symbols data length to an encoding packet.

RFC 6330 specifies in section [4.4.2](https://tools.ietf.org/html/rfc6330#section-4.4.2) how to construct an encoding packet. Below is a transcript of three paragraphs in that section:

> Each encoding packet either contains only source symbols (source packet) or contains only repair symbols (repair packet).  A packet may contain any number of symbols from the same source block. In the case that the last source symbol in a source packet includes padding octets added for FEC encoding purposes, then these octets need not be included in the packet.  Otherwise, each packet MUST contain only whole symbols.

> The Encoding Symbol ID, X, carried in each source packet is the Encoding Symbol ID of the first source symbol carried in that packet. The subsequent source symbols in the packet have Encoding Symbol IDs X+1 to X+G-1 in sequential order, where G is the number of symbols in the packet.

> Similarly, the Encoding Symbol ID, X, placed into a repair packet is the Encoding Symbol ID of the first repair symbol in the repair packet, and the subsequent repair symbols in the packet have Encoding Symbol IDs X+1 to X+G-1 in sequential order, where G is the number of symbols in the packet.

The RFC specifies that an encoding packet may contain multiple (either source or repair) symbols in it. However, the RFC does not specify how to inform the receiver about how many symbols are contained in a received encoding packet, in other words, how to transmit the number G as defined in the last two paragraphs.

We added in OpenRQ a way to provide the number G to a receiver, and since it is not specified in the RFC how to do this, there is no danger of being non-compliant.

**Comment by Bastian35022** [comment]
Hi Ricardo, thanks a lot for your extensive answer.

Adding a way to get the data without the symbols size bytes would be great!

More generally, as long as the lower layers handle packet reception correctly and only pass complete packets to the decoder, the decoder should be able to determine the number of symbols from the packet size and the symbol size, which is always constant for an object.

After some more code-digging, i saw that OpenRQ already offers a lot of flexibility in the decoder, which also supports this approach. Hooray! =)
